version: '2.9'
services:
  #Django App
  backend:
  container_name: django
  build: .
  volumes:
    - .:/app
  ports:
    - 8000:8000
  depends_on:
    - db
    - redis

#Database (Postgres)
db:
  image: postgres
  container_mame: postgressql
  restart: always
  environment:
    POSTGRES_DB: ninerogues_db
    POSTGRES_USER: ninerogues
    POSTGRES_PASSWORD: postgres
  ports:
    - 5432:5432
  volumes:
    - .dbdata:/var/lib/postgresql

#Redis
redis:
  image: redis
  container_mame: Redis
  ports:
    - 6379:6379