version: '3.8'
services:
  #Django App
  brmz_backend:
    container_name: django
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - brmz_db
      - brmz_redis

  #Database (Postgres)
  brmz_db:
    image: postgres
    container_name: postgressql
    restart: always
    environment:
      POSTGRES_DB: brmz_db
      POSTGRES_USER: brmz
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - .dbdata:/var/lib/postgresql

  #Redis
  brmz_redis:
    image: redis
    container_name: Redis
    ports:
      - 6379:6379